/**
 * PdfParserView 스타일 정의
 */
export function getStyles() {
  return {
    overlay: {
      width: '100%',
      height: '100%',
      background: '#f1f5f9',
      display: 'flex',
      flexDirection: 'column',
      fontFamily: 'sans-serif',
      minHeight: 0,
      overflow: 'hidden',
    },
    header: {
      height: '56px',
      background: '#fff',
      borderBottom: '1px solid #e2e8f0',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 24px',
      flexShrink: 0,
      zIndex: 20,
    },
    headerLeft: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
    },
    headerIcon: {
      width: '32px',
      height: '32px',
      background: '#2563eb',
      borderRadius: '8px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: '16px',
      fontWeight: 600,
      color: '#1e293b',
    },
    headerRight: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    btnGhost: {
      fontSize: '12px',
      background: '#eff6ff',
      color: '#2563eb',
      border: '1px solid #bfdbfe',
      padding: '6px 12px',
      borderRadius: '6px',
      cursor: 'pointer',
      fontWeight: 500,
    },
    btnGhostRed: {
      fontSize: '12px',
      background: '#fef2f2',
      color: '#dc2626',
      border: '1px solid #fecaca',
      padding: '6px 12px',
      borderRadius: '6px',
      cursor: 'pointer',
      fontWeight: 500,
    },
    btnGhostGray: {
      fontSize: '12px',
      background: '#f8fafc',
      color: '#475569',
      border: '1px solid #e2e8f0',
      padding: '6px 12px',
      borderRadius: '6px',
      cursor: 'pointer',
      fontWeight: 500,
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
    },
    main: {
      display: 'flex',
      flex: 1,
      overflow: 'hidden',
    },
    sidebar: {
      width: '192px',
      background: '#fff',
      borderRight: '1px solid #e2e8f0',
      display: 'flex',
      flexDirection: 'column',
      flexShrink: 0,
    },
    sidebarHead: {
      padding: '12px',
      borderBottom: '1px solid #f1f5f9',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      background: '#f8fafc',
      flexShrink: 0,
    },
    sidebarHeadText: {
      fontSize: '11px',
      fontWeight: 700,
      color: '#94a3b8',
      textTransform: 'uppercase',
      letterSpacing: '0.05em',
    },
    uploadArea: {
      padding: '12px',
      borderBottom: '1px solid #f1f5f9',
      flexShrink: 0,
    },
    uploadBox: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      border: '1px dashed #cbd5e1',
      borderRadius: '8px',
      padding: '12px',
      background: '#fff',
      cursor: 'pointer',
      position: 'relative',
    },
    uploadInput: {
      position: 'absolute',
      inset: 0,
      opacity: 0,
      cursor: 'pointer',
      width: '100%',
      height: '100%',
    },
    thumbScroll: {
      flex: 1,
      overflowY: 'auto',
      padding: '12px',
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
    },
    thumbWrap: {
      position: 'relative',
    },
    thumbBtn: (isActive) => ({
      position: 'relative',
      width: '100%',
      textAlign: 'left',
      cursor: 'pointer',
      background: 'none',
      border: 'none',
      padding: '4px',
      borderRadius: '8px',
      outline: isActive ? '2px solid #3b82f6' : 'none',
      opacity: isActive ? 1 : 0.6,
    }),
    thumbInner: {
      background: '#fff',
      border: '1px solid #e2e8f0',
      borderRadius: '4px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    thumbBadge: (isActive) => ({
      position: 'absolute',
      left: '-4px',
      top: 0,
      fontSize: '10px',
      color: '#fff',
      padding: '0 4px',
      borderRadius: '0 4px 4px 0',
      background: isActive ? '#3b82f6' : '#94a3b8',
    }),
    thumbActions: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      display: 'flex',
      alignItems: 'center',
      gap: '6px',
      zIndex: 20,
    },
    iconBtn: (color = '#475569') => ({
      padding: '8px',
      background: 'rgba(255,255,255,0.95)',
      border: '1px solid #e2e8f0',
      borderRadius: '50%',
      boxShadow: '0 1px 4px rgba(0,0,0,0.12)',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      color,
    }),
    iconBtnRed: {
      padding: '8px',
      background: 'rgba(255,255,255,0.95)',
      border: '1px solid #fecaca',
      borderRadius: '50%',
      boxShadow: '0 1px 4px rgba(0,0,0,0.12)',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      color: '#dc2626',
    },
    content: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      background: '#e2e8f0',
      position: 'relative',
      overflow: 'hidden',
    },
    toolbar: {
      background: '#fff',
      borderBottom: '1px solid #e2e8f0',
      padding: '12px 24px',
      display: 'flex',
      gap: '24px',
      alignItems: 'center',
      flexShrink: 0,
    },
    toolbarLabel: {
      fontSize: '11px',
      fontWeight: 700,
      color: '#94a3b8',
      textTransform: 'uppercase',
      letterSpacing: '0.05em',
      marginBottom: '8px',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    fieldBtnActive: {
      padding: '6px 12px',
      borderRadius: '6px',
      fontSize: '12px',
      fontWeight: 500,
      border: '1px solid #2563eb',
      background: '#eff6ff',
      color: '#1d4ed8',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      outline: '1px solid #2563eb',
    },
    fieldBtnInactive: {
      padding: '6px 12px',
      borderRadius: '6px',
      fontSize: '12px',
      fontWeight: 500,
      border: '1px solid #cbd5e1',
      background: '#fff',
      color: '#475569',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    btnPrimary: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '8px',
      padding: '8px 16px',
      borderRadius: '6px',
      fontSize: '14px',
      fontWeight: 500,
      background: '#2563eb',
      color: '#fff',
      border: 'none',
      cursor: 'pointer',
      boxShadow: '0 1px 2px rgba(0,0,0,0.08)',
    },
    btnPrimaryDisabled: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '8px',
      padding: '8px 16px',
      borderRadius: '6px',
      fontSize: '14px',
      fontWeight: 500,
      background: '#93c5fd',
      color: '#fff',
      border: 'none',
      cursor: 'not-allowed',
    },
    statusBadge: {
      fontSize: '11px',
      background: '#f8fafc',
      color: '#475569',
      border: '1px solid #e2e8f0',
      padding: '6px 12px',
      borderRadius: '6px',
    },
    pdfScrollArea: {
      flex: 1,
      overflow: 'auto',
      padding: '32px',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'flex-start',
      background: '#e2e8f0',
    },
    pdfCanvas: (crosshair) => ({
      background: '#fff',
      boxShadow: '0 10px 40px rgba(0,0,0,0.2)',
      borderRadius: '2px',
      position: 'relative',
      cursor: crosshair ? 'crosshair' : 'default',
    }),
    emptyState: {
      display: 'flex',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyInner: {
      textAlign: 'center',
      color: '#94a3b8',
      maxWidth: '320px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    },
    emptyIcon: {
      height: '80px',
      width: '80px',
      borderRadius: '50%',
      background: '#fff',
      boxShadow: '0 1px 4px rgba(0,0,0,0.08)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: '16px',
    },
  };
}

export default getStyles;
